spring:
  profiles:
    active: ${PROFILE}

  data:
    jpa:
      repositories:
        bootstrap-mode: deferred # 비동기적 리포지토리 검사
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      repositories:
        enabled: false

server:
  port: 8080

--- #jwt
jwt:
  secret-key: ${JWT_SECRET_KEY}
  issuer: ${JWT_ISSUER}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

--- #cookie
cookie:
  refresh-expirtaion: ${COOKIE_REFRESH_EXPIRATION}

--- # swagger
springdoc:
  swagger-ui:
    operations-sorter: method
